import os
# We use the "os" library to read settings (like our API key) stored on our computer.
from dotenv import load_dotenv
# "dotenv" loads the key-value pairs from our ".env" file so Python can read them.
from fastapi import FastAPI, HTTPException, Request
# "FastAPI" is the library we use to create our web API.
# "HTTPException" lets us return error messages (like 400 or 500) if something goes wrong.
from fastapi.responses import RedirectResponse
# "RedirectResponse" lets us automatically redirect visitors from the root "/" path to the interactive docs "/docs".
from pydantic import BaseModel
# "BaseModel" helps us define what our incoming JSON request should look like.
from groq import Groq
# "Groq" is the official client library used to talk to Groq's high-speed AI models.

# ==========================================
# 1. LOAD CONFIGURATION & ENVIRONMENT FILES
# ==========================================
# Load variables from the .env file in the same directory.
load_dotenv()

# Get the Groq API key from the environment.
groq_api_key = os.getenv("GROQ_API_KEY")

# ==========================================
# 2. INITIALIZE SERVICES (FastAPI & Groq)
# ==========================================
# Create the FastAPI app instance.
# This is our main web application that listens for incoming visits and requests.
app = FastAPI(
    title="Minimal AI Chatbot API",
    description="""
### 🌟 Welcome Student! 
This page lets you test our AI Chatbot API. Follow these simple steps to try it out:

1. Click on the green **POST /ask** bar below.
2. Click the **Try it out** button on the right.
3. Change the text in the prompt box (for example: `"Explain photosynthesis"`).
4. Click the blue **Execute** button.
5. Scroll down to the **Server response** area to see the AI's reply in JSON format!
    """,
    version="1.0.0"
)

# Initialize the Groq AI client with our API key.
# We wrap this in a try-except block so that the app won't crash if the key is missing.
try:
    groq_client = Groq(api_key=groq_api_key)
except Exception as e:
    print(f"Error starting Groq client: {e}")
    groq_client = None

# ==========================================
# 3. DEFINE DATA MODELS (Pydantic)
# ==========================================
# When someone sends a request to our chatbot, they must send a JSON body containing a "prompt" text.
# Example: { "prompt": "What is 2 + 2?" }
class AskRequest(BaseModel):
    prompt: str  # We expect a string key named "prompt"

# ==========================================
# 4. DEFINE WEB SERVER API ROUTES
# ==========================================

# --- GET ROUTE (Redirect to interactive documentation) ---
# When you open the API in your web browser (at the root "/"), this function runs.
# It automatically redirects the visitor to the "/docs" page so they see the interactive UI immediately.
@app.get("/")
def welcome_message():
    return RedirectResponse(url="/docs")


# --- POST ROUTE (Sends user prompt to Groq AI) ---
# This is the actual endpoint that accepts a user prompt, sends it to the Groq AI, and returns the response.
@app.post("/ask")
def ask_ai(request_data: AskRequest):
    # 1. Check if the Groq API key is set
    if not groq_api_key or not groq_client:
        raise HTTPException(
            status_code=500,
            detail="Groq API Key is missing. Please set GROQ_API_KEY in your .env file."
        )

    # 2. Clean the input prompt text by removing unnecessary spaces
    user_prompt = request_data.prompt.strip()

    # 3. Check if the prompt is empty
    if not user_prompt:
        raise HTTPException(
            status_code=400,
            detail="The prompt cannot be empty. Please enter a question."
        )

    try:
        # 4. Request a text completion from Groq's Llama model
        completion = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": "You are a helpful, friendly, and concise AI assistant."
                },
                {
                    "role": "user",
                    "content": user_prompt
                }
            ]
        )

        # 5. Extract the text answer generated by the AI
        ai_response = completion.choices[0].message.content

        # 6. Return the response as JSON: { "response": "AI's text answer" }
        return {"response": ai_response}

    except Exception as e:
        # If the API call fails, return an HTTP 500 server error
        raise HTTPException(
            status_code=500,
            detail=f"Failed to communicate with Groq AI: {str(e)}"
        )
